import { useWallet } from "@solana/wallet-adapter-react";
import { api } from "@src/utils/api";
import Head from "next/head";
export default function Home() {
  const data = useWallet();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <p className="text-2xl text-white">
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </p>
        <p className="text-2xl text-white">{data?.publicKey?.toBase58()}</p>
      </main>
    </>
  );
}
